spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5678/database
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  batch:
    job:
      enabled: true
      name: financialProductSyncJob
    jdbc:
      initialize-schema: always




collector:
  enabled: true
  source: ALL
  mode: normalize_only
  normalizer-version: 13
  reader-page-size : 500
  unseen-disable-period : 1

  ontong-youth:
    base-url: https://www.youthcenter.go.kr
    api-key: ${ONTONG_YOUTH_API_KEY:}
    page-size : 100

  fss:
    base-url: https://finlife.fss.or.kr
    api-key: ${FSS_API_KEY:}
    page-size : 100

  bank-product:
    seeds:
      - bank-code: KB
        keyword: 청년도약계좌
        aliases:
          - 청년 자산형성 지원(청년도약계좌)
        title: 청년도약계좌
        url: https://obank.kbstar.com/quics?cc=b061496%3Ab061645&page=C016613&prcode=DP01001576
        enabled: true
      - bank-code: WOORI
        keyword: 청년도약계좌
        title: 우리 청년도약계좌
        url: https://spot.wooribank.com/pot/Dream?PRD_CD=P010002512&PRD_YN=Y&cc=c007095%3Ac009166%3Bc012263%3Ac012399&withyou=PODEP0019
        enabled: false

